### ISSUE TITLE
[Feature] Add Workflow to Publish to JSR

### ISSUE THREAD

**Issue by liblaf** [liblaf/copier-typescript#2]
### 🥰 Feature Description

...

### 🧐 Proposed Solution

```yaml
jobs:
  publish-jsr:
    name: Publish (JSR)
    permissions:
      id-token: write
    needs:
      - detect
    if: (github.event_name == 'release' || startsWith(github.ref, 'refs/tags/v')) && needs.detect.outputs.jsr == 'true'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-publish-jsr
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: |-
          bun install
          bun pm bin >> "$GITHUB_PATH"
      - name: Publish
        run: bunx jsr publish
```
